__version__ = '1.2.3'
__title__ = 'testclass'
__author__ = 'Peter White'
__description__ = 'Package to help create test modules'
__email__ = 'pwhite@delpwhite.org'
__license__ = 'MIT'
__copyright__ = 'Copyright 2022 Peter White'
