__version__ = '0.5.4'
__title__ = 'testclass'
__author__ = 'Peter White'
__description__ = 'Package to help create test modules'
__email__ = 'pwhite@delpwhite.org'
__license__ = 'MIT'
__copyright__ = 'Copyright 2019 Peter White'
